export const PATH = {
  root: '/',
  mypage: '/mypage',
  notification: '/notification',
  login: '/login',
  search: '/search',
  filter: '/filter',
  schedule: '/schedule',
  editSchedule: '/schedule/:id',
  signup: '/signup',
  findPassword: 'find-password',
  detail: '/detail/',
  post: '/posts/:id',
  changePassword: '/change-password',
  commentModal: '/comment-modal',
  map: '/map/:id',
  setup: '/setup',
  notfound: '*',
};
